# Generated by Django 4.1.7 on 2023-04-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tienda', '0002_rename_datosusuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='perfilUsuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='profesionUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='emailUsuario',
            field=models.CharField(default='xxxx.yyyy@zzzz.com', max_length=32),
        ),
    ]
