# Generated by Django 4.1.7 on 2023-04-14 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tienda', '0004_alter_usuario_tipousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='emailUsuario',
            field=models.CharField(default='xxxx.yyyy@zzzz.bbb', max_length=32),
        ),
    ]
