# Generated by Django 4.1.7 on 2023-04-14 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tienda', '0008_alter_usuario_emailusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='emailUsuario',
        ),
    ]
