# Generated by Django 4.1.7 on 2023-04-15 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_tienda', '0009_remove_usuario_emailusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(default='', max_length=32)),
                ('codigoProducto', models.CharField(default='COD-0000', max_length=8)),
                ('precioCompra', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('precioVenta', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('userRelacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
