# Generated by Django 4.1.7 on 2023-04-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tienda', '0010_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='precioCompra',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precioVenta',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
        ),
    ]
